# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/prjstart/main.go
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Env.VERSION }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

archives:
- name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Version }}.{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    386: i386
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip
      
brews:
  - github:
      owner: crosseyed
      name:  prjstart-tap
    folder: Formula
    homepage:  https://github.com/crosseyed/prjstart
    description: Rapid boilerplate tool
    test: |
      system "#{bin}/prjstart -v"
    skip_upload: true
    url_template: "https://github.com/crosseyed/{{ .ProjectName }}/releases/download/{{ .Env.VERSION }}/{{ .ArtifactName }}"

nfpms:
  - file_name_template: '{{ .ProjectName }}-{{ .Version }}.{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: macos
      386: i386
      amd64: x86_64
    homepage:  https://github.com/crosseyed/prjstart
    description: Rapid boilerplate tool
    maintainer: Dexter Plameras
    license: Apache 2
    vendor: Project Start
    formats:
    - deb
    - rpm
    dependencies:
    - git
