language: go
go:
  - "1.13.4"

cache:
  directories:
    - $GOPATH

jobs:
  include:
    - stage: depsdev
      script: make depsdev
    - stage: test
      script: make test

deploy:
  - provider: script
    skip_cleanup: true
    script: make release
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
