language: go
go:
  - "1.13.4"

cache:
  directories:
    - $GOPATH

jobs:
  include:
    - stage: depsdev
      script: make depsdev
    - stage: test
      script: make test
    - stage: release
      script: make release

stages:
  - devdeps
  - test
  - name: release
    if: tag =~ ^v\d+\.\d+(?:\.\d+)?$
