name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up cache
      uses: actions/cache@v1
      with:
        path: ~/go
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Git checkout
      uses: actions/checkout@v2
    
    - name: Build
      run: |
        export PATH=$(go env GOPATH)/bin:$PATH
        make depsdev
        make deps
        make build
    
    - name: Unit tests
      run: |
        export PATH=$(go env GOPATH)/bin:$PATH
        git config --global user.email "noreply@github.com"
        git config --global user.name "Unit Testing"
        make unit
    
    - name: Code coverage
      run: |
        export PATH=$(go env GOPATH)/bin:$PATH
        # TODO - Can't spin up a server in github
        # make codecoverage
    
    - name: Code complexity
      run: |
        export PATH=$(go env GOPATH)/bin:$PATH
        make codecomplexity
